### ISSUE TITLE
Bug report on running

### ISSUE THREAD

**Issue by JokerYan** [AY1920S1-CS2113-T13-1/main#238]
Hi guys, I am one of the testers testing your product this afternoon. 
I am using java 11 but failed to run your program. Maybe you would like to take a look before the actual testing starts?
![image](https://user-images.githubusercontent.com/18729314/67998871-ee9aea00-fc94-11e9-8797-c6673196f3aa.png)

**Comment by JokerYan** [comment]
My system is Windows, FYI

**Comment by Dkenobi** [comment]
Hi, could you try creating a directory and place the jar file inside and run again? Probably your Download directory is polluted with .json file. Thanks.

**Comment by JokerYan** [comment]
Great, it is working. Thank you!
